apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
    service: frontend
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        app: frontend
        service: frontend
    spec:
      containers:
      - name: udagram-frontend
        envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: env-secret
        image: rajivrrp/udagram-frontend:v3
        ports:
          - containerPort: 80
            protocol: TCP
