apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverseproxy
    service: reverseproxy
  name: reverseproxy-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
        service: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: env-secret
        image: rajivrrp/reverseproxy:v3
        ports:
          - containerPort: 8080
            protocol: TCP
